[build]
builder = "nixpacks"

[deploy]
startCommand = "cp .env.example .env && php artisan key:generate && touch database/database.sqlite && php artisan migrate --force && php artisan db:seed --force && php artisan serve --host=0.0.0.0 --port=$PORT"
